name: jmessage_flutter
description: JIGUANG officially supported JMessage Flutter plugin (Android & iOS). 极光推送官方支持的 Flutter 插件（Android & iOS）(https://www.jiguang.cn).
version: 2.0.7
homepage: https://www.jiguang.cn

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  platform: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.7
flutter:
  plugin:
    platforms:
      android:
        package: com.jiguang.jmessageflutter
        pluginClass: JmessageFlutterPlugin
      ios:
        pluginClass: JmessageFlutterPlugin